apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: example-net
  namespace: rook-ceph

spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPools:
    - failureDomain: host
      replicated:
        size: 3
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
