apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # https://hub.docker.com/r/ceph/ceph/tags
    image: ceph/ceph:v14.2.5
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
  dashboard:
    enabled: true
    port: 8080
    ssl: false
  monitoring:
    enabled: false
  network:
    hostNetwork: false
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: "sdb"
    config:
      osdsPerDevice: "1"
  placement:
    mgr:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/master"
              operator: In
              values:
              - "true"
